In [26]:
import numpy as np

a = np.arange(4.1,10.7)

print (a)


[ 4.1  5.1  6.1  7.1  8.1  9.1 10.1]


In [6]:
b = np.arange(41)

In [7]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [27]:
c = np.arange(5,9,3)

print(c)

[5 8]


In [39]:
a1 = np.array([5,5,4,6.1])

print (a1)

type(a1)

[5.  5.  4.  6.1]


numpy.ndarray

In [47]:
b1 = np.array([[5,5,4],[2,3,4],[6,4,2]])

print (b1)


len(b1)
b1[2]


[[5 5 4]
 [2 3 4]
 [6 4 2]]


array([6, 4, 2])

In [51]:
c1 = np.empty(8)

print(c1)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [56]:
x1 = np.array([2,5,8,7])

print(x1)

[2 5 8 7]
